MyMlModel/urls.py
from django.contrib import admin
from django.urls import path, include
from myMLtestapp.views import my_page

urlpatterns = [
    path('', my_page, name='my_page'),
    path('admin/', admin.site.urls),
    path('api/', include('myMLtestapp.urls')),
]

myMLtestapp/urls.py
from django.urls import path
from .api import (heart_disease_name, heart_disease_create,
                  HeartDiseaseApi, heart_disease_list, SubmitForm,
                  heart_disease_detail, heart_disease_delete, HeartDiseaseUpdate)

# submit_form,

app_name = 'myMLtestapp'

urlpatterns = [
    path('patients_list/', heart_disease_list, name="heart_disease_list"),
    path('fdetails/<int:pk>/', heart_disease_detail, name="heart_disease_detail"),
    path('submit-form/', SubmitForm.as_view(), name="submit_form"),
    # path('submit-form/', submit_form, name="submit_formFBV"),
    path('fname/<str:name>/', heart_disease_name, name="heart_disease_name"),
    path('fcreate/', heart_disease_create, name="heart_disease_create"),
    # path('Clist/<str:user_id>', HeartDiseaseApi.as_view(), name="heart_disease_c_list"),
    path('each_patient/<str:user_id>/', HeartDiseaseApi.as_view(), name="heart_disease_c_list"),
    path('patient_delete/<int:pk>/', heart_disease_delete, name="heart_disease_delete"),
    path('patient_update/<int:pk>/', HeartDiseaseUpdate.as_view(), name="heart_disease_update"),

]

myMLtestapp/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User


class HeartDisease(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    user_id = models.CharField(max_length=30, null=True)
    HighBP = models.BooleanField()
    HighChol = models.BooleanField()
    CholCheck = models.BooleanField()
    BMI = models.IntegerField(
        validators=[
            MinValueValidator(10),
            MaxValueValidator(50),
        ]
    )
    Smoker = models.BooleanField()
    Stroke = models.BooleanField()
    DIABETES_CHOICES = (
        (0, 'NO'),
        (1, 'Type 1'),
        (2, 'Type 2'),
    )
    Diabetes = models.IntegerField(choices=DIABETES_CHOICES)
    PhysActivity = models.BooleanField()
    Veggies = models.BooleanField()
    NoDocbcCost = models.BooleanField()
    GenHlth = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    MentHlth = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(30)])
    PhysHlth = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(30)])
    DiffWalk = models.BooleanField()
    SEX_CHOICES = (
        ('M', 'MALE'),
        ('F', 'FEMALE'),
    )
    Sex = models.CharField(choices=SEX_CHOICES, max_length=1)
    Age = models.IntegerField()
    Education = models.IntegerField()
    Income = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(8)])
    result = models.BooleanField(null=True)
    submitted_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.first_name

myMLtestapp/views.py
from django.shortcuts import render


# Create your views here.
def my_page(request):
    return render(request, 'base.html')


def my_view(request):
    id_value = 1  # Replace with the actual id value
    context = {'id_value': id_value}
    return render(request, 'base.html', context)

templates/base.html
{# create a simple html page #}

<!doctype html>
<html lang="">
<head>

    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>My Page</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<h1>My Page</h1>
<p>This is my page.</p>
<p>For visiting my api pages click this </p>
<p> For viewing patients lists <a href="{% url 'myMLtestapp:heart_disease_list' %}">Click here</a></p>
<p> For viewing submit form <a href="{% url 'myMLtestapp:submit_form' %}">Click here</a></p>
{#<p> For viewing submit form <a href="{% url 'myMLtestapp:submit_formFBV' %}">Click here</a></p>#}
{#<p> For viewing patient page by id <a href="{% url 'myMLtestapp:heart_disease_c_list' id=id_value %}">Click here</a>#}
{#</p>#}
<p>For visiting admin page click this </p>
<p> Admin Page <a href="{% url 'admin:index' %}">Click here</a></p>

</body>
</html>